namespace MyTelescope.SolarSystem.Helpers.Seeder
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Constants;
    using Enums;
    using Extensions;
    using Models.CelestialObject;
    using Utilities.Helpers;
    using Utilities.Models;

    public static class CelestialObjectSeedHelper
    {
        public static CelestialObjectModel GetSun()
        {
            return new CelestialObjectModel(
                CelestialObject.Sun.ToConstant(),
                true,
                CelestialObjectTypeSeedHelper.GetCelestialObjectTypes().Single(x => x.Code == CelestialObjectTypeConstants.Star).Id,
                null,
                "#fcbc22",
                "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Sun_white.jpg/580px-Sun_white.jpg",
                1988500,
                141200000,
                695700,
                695700,
                0,
                609.12,
                0,
                0,
                0,
                0,
                0,
                0,
                1408,
                274,
                0,
                0,
                0,
                5772,
                0,
                9,
                false,
                147.1,
                149.6,
                152.1,
                1952,
                1887,
                0)
            {
                Id = new Guid("487C58A4-796E-4F15-8A0C-70BED46D6008")
            };
        }

        public static CelestialObjectPositionModel GetSunPosition()
        {
            return GetSunPosition(DateTime.Today.Date.GetClosestUtcZeroTime());
        }

        public static CelestialObjectPositionModel GetSunPosition(DateTimeOffset referenceDate)
        {
            return new CelestialObjectPositionModel(GetSun().Id, referenceDate, new LocationModel(0, 0, 0), 0, 0);
        }

        public static List<CelestialObjectModel> GetPlanets()
        {
            var sunId = GetSun().Id;
            var planetTypeId = CelestialObjectTypeSeedHelper.GetCelestialObjectTypes().Single(x => x.Code == CelestialObjectTypeConstants.Planet).Id;

            return new List<CelestialObjectModel>
            {
                new CelestialObjectModel(
                    CelestialObject.Mercury.ToConstant(),
                    true,
                    planetTypeId,
                    sunId,
                    "#bcb49b",
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Mercury_in_color_-_Prockter07-edit1.jpg/450px-Mercury_in_color_-_Prockter07-edit1.jpg",
                    0.33011,
                    6.083,
                    2439.7,
                    2439.7,
                    87.969,
                    1407.6,
                    4222.6,
                    115.88,
                    57.91,
                    0.2056,
                    46.00,
                    69.82,
                    5427,
                    3.7,
                    3.7,
                    4.3,
                    9082.7,
                    439.6,
                    7,
                    0,
                    false,
                    77.3,
                    91.70,
                    221.9,
                    13,
                    4.5,
                    -1.9),

                new CelestialObjectModel(
                    CelestialObject.Venus.ToConstant(),
                    true,
                    planetTypeId,
                    sunId,
                    "#fffacd",
                    "https://upload.wikimedia.org/wikipedia/commons/e/e5/Venus-real_color.jpg",
                    4.8675,
                    92.843,
                    6051.8,
                    6051.8,
                    224.701,
                    -5832.6,
                    2802.0,
                    583.92,
                    108.21,
                    0.0067,
                    107.48,
                    108.94,
                    5243,
                    8.87,
                    8.87,
                    10.36,
                    2601.3,
                    226.6,
                    13,
                    0,
                    false,
                    38.2,
                    41.44,
                    261,
                    66.0,
                    9.7,
                    -4.6),
                new CelestialObjectModel(
                    CelestialObject.Earth.ToConstant(),
                    false,
                    planetTypeId,
                    sunId,
                    "#2b4c75",
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/The_Earth_seen_from_Apollo_17.jpg/450px-The_Earth_seen_from_Apollo_17.jpg",
                    5.9724,
                    108.321,
                    6378.1,
                    6356.8,
                    365.256,
                    23.9345,
                    24,
                    0,
                    149.60,
                    0.0167,
                    147.09,
                    152.10,
                    5514,
                    9.8,
                    9.78,
                    11.2,
                    1361.0,
                    254.0,
                    20,
                    1,
                    false,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0),
                new CelestialObjectModel(
                    CelestialObject.Mars.ToConstant(),
                    false,
                    planetTypeId,
                    sunId,
                    "#9B8242",
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/OSIRIS_Mars_true_color.jpg/550px-OSIRIS_Mars_true_color.jpg",
                    0.64171,
                    16.318,
                    3396.2,
                    3376.2,
                    686.980,
                    24.622,
                    24.6597,
                    779.94,
                    227.92,
                    0.0935,
                    206.62,
                    249.23,
                    3933,
                    3.71,
                    3.69,
                    5.03,
                    586.2,
                    209.8,
                    30,
                    2,
                    false,
                    55.7,
                    78.39,
                    401.3,
                    25.1,
                    3.5,
                    -2.91),
                new CelestialObjectModel(
                    CelestialObject.Jupiter.ToConstant(),
                    false,
                    planetTypeId,
                    sunId,
                    "#ffcc99",
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Jupiter_and_its_shrunken_Great_Red_Spot.jpg/660px-Jupiter_and_its_shrunken_Great_Red_Spot.jpg",
                    1898.19,
                    143128,
                    71492,
                    66854,
                    4332.589,
                    9.9250,
                    9.9259,
                    398.88,
                    778.57,
                    0.0489,
                    740.52,
                    816.62,
                    1326,
                    24.79,
                    23.12,
                    59.5,
                    50.26,
                    109.9,
                    0,
                    67,
                    true,
                    588.5,
                    628.76,
                    968.1,
                    50.1,
                    29.8,
                    -2.94),
                new CelestialObjectModel(
                    CelestialObject.Saturn.ToConstant(),
                    false,
                    planetTypeId,
                    sunId,
                    "#fffacd",
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Saturn_during_Equinox.jpg/660px-Saturn_during_Equinox.jpg",
                    568.34,
                    82713,
                    60268,
                    54364,
                    10759.22,
                    10.656,
                    10.656,
                    378.09,
                    1433.53,
                    0.0565,
                    1352.55,
                    1514.50,
                    687,
                    10.44,
                    8.96,
                    35.5,
                    14.82,
                    81.0,
                    0,
                    62,
                    true,
                    1195.5,
                    1277.42,
                    1658.5,
                    20.1,
                    14.5,
                    0.43),
                new CelestialObjectModel(
                    CelestialObject.Uranus.ToConstant(),
                    false,
                    planetTypeId,
                    sunId,
                    "#f5ffff",
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Uranus2.jpg/520px-Uranus2.jpg",
                    86.813,
                    6833,
                    25559,
                    24973,
                    30685.4,
                    -17.24,
                    17.24,
                    369.66,
                    2872.46,
                    0.0457,
                    2741.30,
                    3003.62,
                    1271,
                    8.87,
                    8.69,
                    21.3,
                    3.69,
                    58.1,
                    0,
                    27,
                    true,
                    2581.9,
                    2719.99,
                    3157.3,
                    4.1,
                    3.3,
                    5.32),
                new CelestialObjectModel(
                    CelestialObject.Neptune.ToConstant(),
                    false,
                    planetTypeId,
                    sunId,
                    "#b0e0e6",
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Neptune_Full.jpg/550px-Neptune_Full.jpg",
                    102.413,
                    6254,
                    24764,
                    24341,
                    60.189,
                    16.11,
                    16.11,
                    367.49,
                    4495.06,
                    0.0113,
                    4444.45,
                    4545.67,
                    1638,
                    11.15,
                    11.00,
                    23.5,
                    1.508,
                    46.6,
                    3411,
                    14,
                    true,
                    4305.9,
                    4347.31,
                    4687.3,
                    2.4,
                    2.2,
                    7.78),
                new CelestialObjectModel(
                    CelestialObject.Pluto.ToConstant(),
                    false,
                    planetTypeId,
                    sunId,
                    "#837d6c",
                    "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Nh-pluto-in-true-color_2x_JPEG-edit-frame.jpg/450px-Nh-pluto-in-true-color_2x_JPEG-edit-frame.jpg",
                    0.01303,
                    0.697,
                    1187,
                    1187,
                    90560,
                    -153.2928,
                    153.2928,
                    366.73,
                    5906.38,
                    0.2488,
                    4436.82,
                    7375.93,
                    1860,
                    0.62,
                    0.62,
                    1.21,
                    0.873,
                    37.5,
                    0,
                    5,
                    false,
                    4284.7,
                    5750.54,
                    7528.0,
                    0.11,
                    0.06,
                    13.65)
            };
        }
    }
}