//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelescope.App.Resources.MyTelescope {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyTelescope.App.Resources.MyTelescope.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amalthea.
        /// </summary>
        public static string Amalthea {
            get {
                return ResourceManager.GetString("Amalthea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparent diameter.
        /// </summary>
        public static string ApparentDiameter {
            get {
                return ResourceManager.GetString("ApparentDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc minutes.
        /// </summary>
        public static string ArcMinutes {
            get {
                return ResourceManager.GetString("ArcMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ′.
        /// </summary>
        public static string ArcMinutesShort {
            get {
                return ResourceManager.GetString("ArcMinutesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc seconds.
        /// </summary>
        public static string ArcSeconds {
            get {
                return ResourceManager.GetString("ArcSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ″.
        /// </summary>
        public static string ArcSecondsShort {
            get {
                return ResourceManager.GetString("ArcSecondsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronomical units.
        /// </summary>
        public static string AstronomicalUnits {
            get {
                return ResourceManager.GetString("AstronomicalUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.U..
        /// </summary>
        public static string AstronomicalUnitsShort {
            get {
                return ResourceManager.GetString("AstronomicalUnitsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black-body temperature.
        /// </summary>
        public static string BlackBodyTemperature {
            get {
                return ResourceManager.GetString("BlackBodyTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callisto.
        /// </summary>
        public static string Callisto {
            get {
                return ResourceManager.GetString("Callisto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celcius.
        /// </summary>
        public static string Celsius {
            get {
                return ResourceManager.GetString("Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degrees.
        /// </summary>
        public static string Degrees {
            get {
                return ResourceManager.GetString("Degrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °.
        /// </summary>
        public static string DegreesShort {
            get {
                return ResourceManager.GetString("DegreesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deimos.
        /// </summary>
        public static string Deimos {
            get {
                return ResourceManager.GetString("Deimos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth.
        /// </summary>
        public static string Earth {
            get {
                return ResourceManager.GetString("Earth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flattening.
        /// </summary>
        public static string Ellipticity {
            get {
                return ResourceManager.GetString("Ellipticity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equatorial radius.
        /// </summary>
        public static string EquatorialRadius {
            get {
                return ResourceManager.GetString("EquatorialRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europa.
        /// </summary>
        public static string Europa {
            get {
                return ResourceManager.GetString("Europa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fahrenheit.
        /// </summary>
        public static string Fahrenheit {
            get {
                return ResourceManager.GetString("Fahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ganymede.
        /// </summary>
        public static string Ganymede {
            get {
                return ResourceManager.GetString("Ganymede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravity.
        /// </summary>
        public static string Gravity {
            get {
                return ResourceManager.GetString("Gravity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inferior orbit.
        /// </summary>
        public static string InferiorOrbit {
            get {
                return ResourceManager.GetString("InferiorOrbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Io.
        /// </summary>
        public static string Io {
            get {
                return ResourceManager.GetString("Io", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jupiter.
        /// </summary>
        public static string Jupiter {
            get {
                return ResourceManager.GetString("Jupiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelvin.
        /// </summary>
        public static string Kelvin {
            get {
                return ResourceManager.GetString("Kelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg/m3.
        /// </summary>
        public static string KgM3 {
            get {
                return ResourceManager.GetString("KgM3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers.
        /// </summary>
        public static string Kilometers {
            get {
                return ResourceManager.GetString("Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km..
        /// </summary>
        public static string KilometersShort {
            get {
                return ResourceManager.GetString("KilometersShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major moon.
        /// </summary>
        public static string MajorMoon {
            get {
                return ResourceManager.GetString("MajorMoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mars.
        /// </summary>
        public static string Mars {
            get {
                return ResourceManager.GetString("Mars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass.
        /// </summary>
        public static string Mass {
            get {
                return ResourceManager.GetString("Mass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string Maximum {
            get {
                return ResourceManager.GetString("Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max..
        /// </summary>
        public static string MaximumShort {
            get {
                return ResourceManager.GetString("MaximumShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean density.
        /// </summary>
        public static string MeanDensity {
            get {
                return ResourceManager.GetString("MeanDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercury.
        /// </summary>
        public static string Mercury {
            get {
                return ResourceManager.GetString("Mercury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles.
        /// </summary>
        public static string Miles {
            get {
                return ResourceManager.GetString("Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi..
        /// </summary>
        public static string MilesShort {
            get {
                return ResourceManager.GetString("MilesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Million.
        /// </summary>
        public static string Million {
            get {
                return ResourceManager.GetString("Million", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        public static string Minimum {
            get {
                return ResourceManager.GetString("Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min..
        /// </summary>
        public static string MinimumShort {
            get {
                return ResourceManager.GetString("MinimumShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor moon.
        /// </summary>
        public static string MinrMoon {
            get {
                return ResourceManager.GetString("MinrMoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon.
        /// </summary>
        public static string Moon {
            get {
                return ResourceManager.GetString("Moon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moons.
        /// </summary>
        public static string Moons {
            get {
                return ResourceManager.GetString("Moons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m/s2.
        /// </summary>
        public static string MS2 {
            get {
                return ResourceManager.GetString("MS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neptune.
        /// </summary>
        public static string Neptune {
            get {
                return ResourceManager.GetString("Neptune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opposition.
        /// </summary>
        public static string Opposition {
            get {
                return ResourceManager.GetString("Opposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string PageBack {
            get {
                return ResourceManager.GetString("PageBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phobos.
        /// </summary>
        public static string Phobos {
            get {
                return ResourceManager.GetString("Phobos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planet.
        /// </summary>
        public static string Planet {
            get {
                return ResourceManager.GetString("Planet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planets.
        /// </summary>
        public static string Planets {
            get {
                return ResourceManager.GetString("Planets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pluto.
        /// </summary>
        public static string Pluto {
            get {
                return ResourceManager.GetString("Pluto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polar radius.
        /// </summary>
        public static string PolarRadius {
            get {
                return ResourceManager.GetString("PolarRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 billion.
        /// </summary>
        public static string Pow10 {
            get {
                return ResourceManager.GetString("Pow10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10^10.
        /// </summary>
        public static string Pow10Number {
            get {
                return ResourceManager.GetString("Pow10Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadrillion.
        /// </summary>
        public static string Pow24 {
            get {
                return ResourceManager.GetString("Pow24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10^24.
        /// </summary>
        public static string Pow24Number {
            get {
                return ResourceManager.GetString("Pow24Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Million.
        /// </summary>
        public static string Pow6 {
            get {
                return ResourceManager.GetString("Pow6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10^6.
        /// </summary>
        public static string Pow6Number {
            get {
                return ResourceManager.GetString("Pow6Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planetary ring system.
        /// </summary>
        public static string RingSystem {
            get {
                return ResourceManager.GetString("RingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellites.
        /// </summary>
        public static string Satellites {
            get {
                return ResourceManager.GetString("Satellites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturn.
        /// </summary>
        public static string Saturn {
            get {
                return ResourceManager.GetString("Saturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar irradiance.
        /// </summary>
        public static string SolarIrradiance {
            get {
                return ResourceManager.GetString("SolarIrradiance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar sytem.
        /// </summary>
        public static string SolarSystem {
            get {
                return ResourceManager.GetString("SolarSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star.
        /// </summary>
        public static string Star {
            get {
                return ResourceManager.GetString("Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        public static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titan.
        /// </summary>
        public static string Titan {
            get {
                return ResourceManager.GetString("Titan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uranus.
        /// </summary>
        public static string Uranus {
            get {
                return ResourceManager.GetString("Uranus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venus.
        /// </summary>
        public static string Venus {
            get {
                return ResourceManager.GetString("Venus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual magnitude.
        /// </summary>
        public static string VisualMagnitude {
            get {
                return ResourceManager.GetString("VisualMagnitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius.
        /// </summary>
        public static string VolumetricMeanRadius {
            get {
                return ResourceManager.GetString("VolumetricMeanRadius", resourceCulture);
            }
        }
    }
}
