//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTelescope.App.Resources.PredictTheSky {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CategoryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CategoryResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyTelescope.App.Resources.PredictTheSky.CategoryResource", typeof(CategoryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aurora.
        /// </summary>
        public static string Aurora {
            get {
                return ResourceManager.GetString("Aurora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auroras.
        /// </summary>
        public static string Auroras {
            get {
                return ResourceManager.GetString("Auroras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comet.
        /// </summary>
        public static string Comet {
            get {
                return ResourceManager.GetString("Comet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comets.
        /// </summary>
        public static string Comets {
            get {
                return ResourceManager.GetString("Comets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iridium flare.
        /// </summary>
        public static string IridiumFlare {
            get {
                return ResourceManager.GetString("IridiumFlare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iridium flares.
        /// </summary>
        public static string IridiumFlares {
            get {
                return ResourceManager.GetString("IridiumFlares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunar eclipse.
        /// </summary>
        public static string LunarEclipse {
            get {
                return ResourceManager.GetString("LunarEclipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunar eclipses.
        /// </summary>
        public static string LunarEclipses {
            get {
                return ResourceManager.GetString("LunarEclipses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meteor shower.
        /// </summary>
        public static string MeteorShower {
            get {
                return ResourceManager.GetString("MeteorShower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meteor showers.
        /// </summary>
        public static string MeteorShowers {
            get {
                return ResourceManager.GetString("MeteorShowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon phase.
        /// </summary>
        public static string MoonPhase {
            get {
                return ResourceManager.GetString("MoonPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moon phases.
        /// </summary>
        public static string MoonPhases {
            get {
                return ResourceManager.GetString("MoonPhases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planet.
        /// </summary>
        public static string Planet {
            get {
                return ResourceManager.GetString("Planet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planets.
        /// </summary>
        public static string Planets {
            get {
                return ResourceManager.GetString("Planets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite.
        /// </summary>
        public static string Satellite {
            get {
                return ResourceManager.GetString("Satellite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellites.
        /// </summary>
        public static string Satellites {
            get {
                return ResourceManager.GetString("Satellites", resourceCulture);
            }
        }
    }
}
